# Generated by Django 2.2.1 on 2019-06-16 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190616_1619'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='ikes',
            new_name='likes',
        ),
    ]
